---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run dmypy run -- src tests
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["-L", "crate,upto,fo"]

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.17
    hooks:
      - id: pymarkdown
        args: ["--config", ".pymarkdown.json", "scan", "."]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
