---
name: ci
'on':
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read

jobs:
  lint-and-typecheck:
    name: Lint, format, and type check
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            uv.lock
      - name: Install dependencies (matches local dev extras)
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev] pre-commit
      - name: Install uv
        run: pip install uv
      - name: Sync deps
        run: uv sync --all-extras --dev
      - name: Run pre-commit hooks
        run: pre-commit run --all-files

  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]  # , windows-latest]
        python-version: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install uv
        run: pip install uv
      - name: Sync deps
        run: uv sync --all-extras --dev
      - name: Tests and coverage
        run: uv run pytest --cov=decree --cov-report=term-missing
