---
name: release
'on':
  push:
    tags: ["v*.*.*"]
permissions:
  id-token: write
  contents: write

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv and tools
        run: pip install uv uv-build
      - name: Set version from tag
        env:
          GIT_TAG: "${{ github.ref_name }}"
        run: python scripts/set_version_from_tag.py
      - name: Build dist
        run: python -m uv_build sdist bdist_wheel
      - name: Publish to PyPI (trusted publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          skip-existing: false
          verify-metadata: true
